# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10b802c2c96330fa1ef1165b5c17c2517337e85c99fc7485b23c14fc57496e94a033463b81f24f775846b7a25fc73da3c7e0493ea3533074dff3eaedc372fdcd

test:
  secret_key_base: eb8aee248c9893612b129b2fc079dc45d4e330bd154513edd2fabbb958575177ef77ff4467c8ad586a94a5737b0889351aec250e2fafc8704c9aa7aadd23b369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
